Description: >
  ECS service running PHP-fpm cotnainer

Parameters:
  VPC:
    Description: ECS cluster VPC
    Type: AWS::EC2::VPC::Id

  Cluster:
    Description: ECS Cluster ID service should run 
    Type: String

  DesiredCount:
    Description: Number of instances 
    Type: Number
    Default: 2

  Path:
    Description: ALB path
    Type: String
    Default: /

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: web-php-service
      NetworkMode: host
      ContainerDefinitions:
        - Name: php-service
          Essential: true
          Image: 510547555808.dkr.ecr.us-east-1.amazonaws.com/incsub-php:v1.0
          Memory: 128

          PortMappings:
            - ContainerPort: 9000


  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 365
